language: cpp

matrix:
  include:

      # GCC
      # - os: linux
      #   addons:
      #     apt:
      #       sources:
      #         - ubuntu-toolchain-r-test
      #       packages:
      #         - g++-5
      #   env:
      #     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"


      #Clang
      - os: linux
        addons:
          apt:
            sources:
              - llvm-toolchain-trusty-5.0
            packages:
              - clang-5.0
        env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd Build
  - make