language: cpp

matrix:
  include:

      #GCC
      - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-4.9.3
        env:
          - MATRIX_EVAL="CC=gcc-4.9.3 && CXX=g++-4.9.3"


      #Clang
      - os: linux
        addons:
          apt:
            sources:
              - llvm-toolchain-trusty-5.0
            packages:
              - clang-7.0
        env:
          - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd Build
  - make